export const projectActivityDetails = {
  $project: {
    id: "$_id",
    _id: 0,
    name: 1,
    slug: 1,
    description: 1,
    distance: 1,
    elevationGain: 1,
    minimumGrade: 1,
    maximumGrade: 1,
    averageGrade: 1,
    timeToComplete: 1,
    difficultyLevel: 1,
    activityType: 1,
    routeType: 1,
    climbCategory: 1,
    photos: 1,
    tags: 1,
    createdAt: 1,
    updatedAt: 1,
    "addressDetails.city": 1,
    "addressDetails.state": 1,
    "addressDetails.country": 1,
    "startCoordinateDetails.latitude": 1,
    "startCoordinateDetails.longitude": 1,
    "endCoordinateDetails.latitude": 1,
    "endCoordinateDetails.longitude": 1,
    createdBy: 1,
    startCoordinate: 1,
    endCoordinate: 1,
    isCreatedByAdmin: 1,
  },
};
